version: "3.9"

services:
  web:
    build:
      context: ./app
      dockerfile: Prod.Dockerfile
    command: gunicorn sovabet.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./env/.env.prod
    depends_on:
      - db
    networks:
      - app-net
  db:
    image: postgres:15-alpine3.17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./env/.env.prod.db
    networks:
      - app-net
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    env_file:
      - ./env/.env.prod.proxy
    depends_on:
      - web
    networks:
      - reverse-proxy-net
      - app-net

volumes:
  postgres_data:
  static_volume:

networks:
  app-net:
  reverse-proxy-net:
    external: true
